version: "3"
 
services:
  bot:
    build:
      context: .
      args:
        - src=./src
    command: bash -c "pm2-docker start process.json"
    restart: on-failure
    env_file:
      - ./docker.env
  redis:
    image: "redis"
    ports:
      - "6379:6379"
